---
title: "mobile"
author: "MARTIN"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries}
library(tidyverse) #For graphing and data cleaning 
library(lubridate) #for date manipulation
library(ggthemes)  #For even more plotting themes
library(ggtext)   #For coloring text in labels
library(naniar)  #for exploring missing labels
library(gghighlight) #For highlighting values
library(maps) # for map data
library(ggthemes) # for themes, including theme_map()
library(gganimate)# for animation

theme_set(theme_minimal()) #ggplot theme
```

```{r}
mobile <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv')
landline <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/landline.csv')
```
```{r}
landline%>%add_n_miss()%>% arrange(desc(n_miss_all))
```

```{r}
landline%>%drop_na(landline_subs)%>%group_by(entity)%>%
  fill(total_pop,gdp_per_cap, .direction = "up")%>%
  ggplot(aes(x=year,
             y=landline_subs,
             group=entity,
             color=continent))+
  geom_line()+facet_wrap(vars(continent))+
  gghighlight(max(landline_subs>100))+
  theme(legend.position = "none")
```


```{r}
world_map <-map_data("world")
```

```{r,eval=FALSE}
world_map <-map_data("world")

landline %>% 
  drop_na(landline_subs) %>% 
  group_by(entity) %>% 
  fill(total_pop, gdp_per_cap, .direction = "up") %>% 
  ggplot() +
  geom_polygon(map = world_map,aes(map_id = entity,fill = landline_subs,group=year)) +
  #This assures the map looks decently nice:
  expand_limits(x = world_map$long, y = world_map$lat) + 
  theme_map() +
  theme(legend.background = element_blank(),
        plot.background = element_rect("gray70")) +
  transition_states(year) +
  labs(title = "Landlines subscriptions per 100 people",
       subtitle = "Year: {closest_state}",
       caption = "Data from Ourworldindata.org, viz by @MARTIN")
  
anim_save("landline_over_time.gif", path = "images/")


```
  
  
```{r} 
  
  world_map <-map_data("world")
  
   mobile%>%
   drop_na(mobile_subs)%>%
   group_by(entity)%>%
   fill(total_pop,gdp_per_cap,.direction="up")%>%
   ggplot()+
   geom_map(map=world_map,
            aes(map_id=entity,fill = mobile_subs,
               group = year)) +
  #This assures the map looks decently nice:
  expand_limits(x = world_map$long, y = world_map$lat) + 
  theme_map() +
  theme(legend.background = element_blank(),
        plot.background = element_rect("#F8F3ED")) +
  transition_states(year) +
  labs(title = "Mobile subscriptions per 100 people",
       subtitle = "Year: {closest_state}",
       caption = "Data from Ourworldindata.org, visual by MARTIN")
  
anim_save("mobile_over_time.gif", path = "images/")
```
  
  
```{r,eval=FALSE}
   world_map <- map_data("world")
landline %>% 
  drop_na(landline_subs) %>% 
  group_by(entity) %>% 
  fill(total_pop, gdp_per_cap, .direction = "up") %>% 
  inner_join(world_map,
             by = c("entity"="region")) %>% 
 # filter(year == 2010) %>% 
  ggplot() +
  geom_polygon(aes(x = long,
                   y = lat,
                   group = group,
                   fill = landline_subs)) +
  #This assures the map looks decently nice:
  expand_limits(x = world_map$long, 
                y = world_map$lat) + 
  theme_map() +
  theme(legend.background = element_blank(),
        plot.background = element_rect("gray70")) +
  transition_time(year) +
  labs(title = "Landlines subscriptions per 100 people",
       subtitle = "Year: {frame_time}",
       caption = "Data from Ourworldindata.org, vISUAL BY MARTIN")
```